### ISSUE TITLE
Проблемы с отображением стен

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#12]
Привет @reef425,

если создать игру с подземельем walls_dungeon:
(launch.py: uncomment line 32, comment line 33)

то можно увидеть что размер иконок стен не нормальный (я бы хотел чтобы оригиналы разных размеров отображались корректно / либо автоматически создавались ресурсы нужного размера).
Кроме того кажется пираты неким образом тоже перенимают иконку стен.

**Comment by reef425** [comment]
Начнем сначала, нужно определиться с разрешениями картинок и ресурсов, желательно вынести все это в декларативный файл cfg.json например. Почему это так важно? На разных разрешениях экрана желательно использовать иконки разной размерности, иначе будет выглядеть не очень красиво.  Поэтому размер клеток жестко забит в ui/GameConfiguration.py инициализируются def setUpUnits(self) это размер для разрешения экрана 1368х768.
В наше случает для объектов размером не равным 128Х128 нужно указывать размер отдельно.

**Comment by reef425** [comment]
Отображение стен работает корректно
