### ISSUE TITLE
Почистить вывод в лог

### ISSUE THREAD

**Issue by reef425** [ikamensh/drim_gam#16]
Очень много выводится не монятного лога, после игры 5 уровней, вывод в лог занимает 2,5 мегабайт. Можно это подпраить?

**Comment by ikamensh** [comment]
Чтобы сделать лог значительно меньше, я избавился от лишних принтов дебага и сделал нормальным поведением событий не-написание лога, лишь избранные события такие как атаки и смерти появляются в логе.
