### ISSUE TITLE
Баг с отображением целевых клеток у активок

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#17]
В текущей версии приложения (21 декабря) цели активок отображаются не там, со смещением (скиншоты приклеплены)
<img width="544" alt="2018-12-21_18h15_03" src="https://user-images.githubusercontent.com/23004004/50346166-180ec380-0564-11e9-958e-5022c0e6ef5d.png">
<img width="293" alt="2018-12-21_21h00_06" src="https://user-images.githubusercontent.com/23004004/50346167-180ec380-0564-11e9-9ace-f20eae0f172c.png">
<img width="245" alt="2018-12-21_21h00_12" src="https://user-images.githubusercontent.com/23004004/50346168-18a75a00-0564-11e9-9315-70d33f663184.png">
<img width="340" alt="2018-12-21_21h00_46" src="https://user-images.githubusercontent.com/23004004/50346171-193ff080-0564-11e9-83b5-48766dd9eb6a.png">

**Comment by reef425** [comment]
Исправил, добавил реализацию поворота
