### ISSUE TITLE
Фантомный юнит(юниты) загораживает свет образуя тень.

### ISSUE THREAD

**Issue by reef425** [ikamensh/drim_gam#20]
Фантомный юнит(юниты) загораживает свет образуя тень.
После того как моб убит остается фантомный юнит, который затеняет собой свет. Свет и тень берутся полностью из логического движка.

![2019-02-12 13-02-27](https://user-images.githubusercontent.com/26322195/52629536-b4f23b00-2edb-11e9-93e8-f0d7911674a6.png)

**Comment by ikamensh** [comment]
Пофиксил - проблема была в кешировании мутируемого сета.
