### ISSUE TITLE
Проблемы на странице прокачка персонажа CharacterPage

### ISSUE THREAD

**Issue by reef425** [ikamensh/drim_gam#22]
Перки

* При доведение до максимального значения Перков, прокачка Мастерства становится не доступным
* При крокачке перков не пересчитваются атрибуты героя(жизнь, мана, ...)
* Нет возможности сбросить на начальное состояние значения перков, нужно ли это?

Мастерства
* Нет возможности сбросить на начальное состояние значения Мастерства.

Копки
* Не реализовано визуальное поведение кнопок.

**Comment by ikamensh** [comment]
это проблемы UI или движка?

**Comment by reef425** [comment]
UI получает данные от движка, Перки и Мастерства реализованы в незаисимых друг от друга объектах.
Вызывается 
character.increase_mastery(mastery)

для перков
```
def perk_up(self, perk):
        self.perk_tree.spent_xp += self.xp_to_levelup(perk)
        perk.current_level += 1

def xp_to_levelup(self, perk):
        return self.perk_tree.cost_to_levelup(perk)

```

**Comment by ikamensh** [comment]
> При крокачке перков не пересчитваются атрибуты героя(жизнь, мана, ...)

надеюсь пофиксил просто с 

```
    def perk_up(self, perk):
        self.perk_tree.spent_xp += self.xp_to_levelup(perk)
        perk.current_level += 1
        self.character.unit.reset()
```

**Comment by ikamensh** [comment]
> Нет возможности сбросить на начальное состояние значения перков, нужно ли это?

Да, это нужно. Я допишу метод резет в прокачке чтобы это делал.
https://github.com/ikamensh/pydolons/issues/28

**Comment by ikamensh** [comment]
> При доведение до максимального значения Перков, прокачка Мастерства становится не доступным

Возможно разберусь с этим создавая юнит тесты в #29 - но ты уже можешь детальнее сказать, прокачка любого мастества будет невозможна? При максе любого перка? вроде я в игре так делал, не замечал.

**Comment by ikamensh** [comment]
> Нет возможности сбросить на начальное состояние значения Мастерства.

Тоесть Character.reset не работает?

**Comment by ikamensh** [comment]
> > Нет возможности сбросить на начальное состояние значения Мастерства.
> 
> Тоесть Character.reset не работает?

воспроизвел и пофиксил.

**Comment by ikamensh** [comment]
Обозначеные проблемы либо решены, либо имеют отдельные issue.
