### ISSUE TITLE
Отображение Walls & Obstacles

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#23]
Добавил стены - Battlefield.walls содержит словарь Cell -> Wall, Wall.icon - иконка которую отображать. Стена занимает всю клекту.

Obstacles "обс" - теперь выполняют роль таких же объектов на поле боя как Unit, но не активных. Может быть больше одного Obstacle на клетке. На клетке могут одновременно стоять и юнит и обс, если им хватает места. В таком случае они образуют стек. Юниты в стеке всегда лежат выше всех обсов.

обс разрушаемы, стены - нет.

**Comment by reef425** [comment]
Стены переделал, по обстакл предлагаю новую ишью, не совсем понятно с механикой. Я думаю недолжно быть так же как с юнитами?

**Comment by ikamensh** [comment]
ок, стены работают, обстакл отдельным тредом сделаем.
