### ISSUE TITLE
Весенняя уборка: файлы

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#25]
Надо убрать файлы по директориям. Попутно надо удалить не используемые файлы.

Файлы ui не должны лежать в корневой директории проекта. Для быстрых тестов рекомендую использовать временные файлы PyCharm (scratches).

Предлагаю постараться упаковать все файлы в иерархию чтобы в ui оказалось не более 7 папок на верхнем уровне. Цифра из пальца, но давай по функционалу постараемся все разделить.

**Comment by reef425** [comment]
Решено. Папки переразложил.

**Comment by ikamensh** [comment]
Как насчет GameLoopThread, LEngine, GameImitation? Они ведь нужны только для ui, отправим их в папку ui?
2. думал не стоит ли вообще создать папку src, и поместить туда все исходники. что думаешь?

**Comment by reef425** [comment]
Перевел последние файлы в ui
