### ISSUE TITLE
Весенняя уборка: типы данных в коде

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#26]
Для удобства в чтении кода и рефакторинге предлагаю добавить типизацию в ui.

чтобы избежать проблем с импортом, используй 
```
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import Unit, Battlefield, ...
```

**Comment by reef425** [comment]
Решено. Типизация добавлена.

**Comment by ikamensh** [comment]
Пара заметок:
типы в первую очередь проставляются в сигнатурах методов. Если у переменной в инициализации есть тип, то он будет автоматически использоваться для филда, в который положена переменная:

```
    def __init__(self, level: BaseLevel):
        super(GameVision, self).__init__()
        self.level = level
```

self.level имеет тип BaseLevel

**Comment by ikamensh** [comment]
Еще типы можно указывать в том числе внутри коллекций
```
    from typing import Dict
    def setWall(self, walls: Dict[Cell, Wall]):
```

**Comment by ikamensh** [comment]
```
    def create_slot(self, slot: Slot, width=128, height=128, space=10)->Element:
        pass
```

может стоит делать raise NotImplementedError()

**Comment by ikamensh** [comment]
Это issue можно закрыть. С типами стало намного легче ориентироваться в коде ui для меня. спасибо!
