### ISSUE TITLE
Obstacles

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#27]
1. Обстаклес образуют стек вместе с юнитами или другими обстаклес на той же клетке.
2. В стеке юниты всегда выше обстаклес
3. Одинокое obstacle тоже отображается как в стеке и не занимает всю клетку в отличии от юнита

**Comment by reef425** [comment]
Вопрос по реализации: Механизм стэка предполагает что любого юнита из движка можно сопоставить с графическим объектом путемя сравнения uid. Можно ли для трупов наследовать uid живого юнита?
```
class Corpse(Obstacle):
        
    def __init__(self, unit: Unit):
        
        self.uid = unit.uid
```

**Comment by reef425** [comment]
1. Обстакле в стэке
2. Юниты отображаютя поверх обстакле
3. Одинокое obstacle уменьшино до 0.5 от начальго размера

**Comment by ikamensh** [comment]
Мне кажется что труп все-таки отдельный объект, поэтому у него должен быть свой uid. Я опасаюсь всяких сложных багов изза совпадения uid. 

Совпадет ли размер одинокого обстакле с его размером в стеке из 2х и более элементов? я бы хотел чтобы это была одна и та же константа.

**Comment by ikamensh** [comment]
Если нужно проверить чей это труп, ты можешь сделать corpse.unit.uid

**Comment by reef425** [comment]
Убрал присвоение uid юнита, добавил ссылку на труп в юните. Дело в том что когда юнит умирает игра получает уведомление с ссылкой на умершего юнита, там же можно получить ссылку на на труп.
