### ISSUE TITLE
Использование слотов

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#3]
@reef425 На данный момент у меня есть ощущение что мы зря используем слоты и сигналы в ивентах и триггерах.

Например:
`def play_movement_anim(t, e):
    ProxyEmit.play_movement_anim.emit({'unit':e.unit,"cell_to":e.cell_to})
`
Мне было не очень просто найти куда этот сигнал идет. Работа всей схемы требует правильной инициализации.

Замена этого кода на следующее работает ровно так же:
`def play_movement_anim(t, e):
    TheUI.singleton.gameRoot.level.unitMoveSlot({'unit':e.unit,"cell_to":e.cell_to})
`

Теперь я могу сразу же найти вызываемую функцию. Кроме того саму функцию можно переписать чтобы использовать аргументы напрямую:

`def play_movement_anim(t, e):
    TheUI.singleton.gameRoot.level.unitMoveSlot(e.unit,e.cell_to)`

Очевидно что использование слотов и сигналов приносит некоторые сложности. Какие преимущества они дают?

**Comment by reef425** [comment]
Это связано с использованием кода одного потока в другом, то есть ---
потокобезопасность. Обычно такие вызовы приводят к непредсказуемым
результатам. В нашем случае не корректно работала систем обновления Ui в
целом, когда происходит смена позиции объекта QGraphicItem ядро запускает
обновление графического представления виджета, то есть по просту мог юнит
умереть или сделать движение и картинка не обновлялась, а оставалась на
месте, точно так же например происходит если рисуем в paint. В Qt такие
вызовы осуществляются через проксирование в qt signals. Следующая
последовательность. В дочернем потоке происходит событие, это событие
генерирует сигнал на который приконекчен слот из основного потока, сработал
сигнал ---> данные передались в слот ---> сработали методы основного
потока. Ничего сложного. Все это гарантирует потокобезопасность. Если все
задокументировать ничего сложного. Кстати если код полностью написан на Qt
результат с вызовами кода внутри другого потока приведет к аналогичным
результатам. С потоками всегда сложный код. А что касается сигналов и
слотов в Qt это как бы основа системы, и нужно один раз понять как это
работает и все.
Жду вопросов.😊

чт, 4 окт. 2018 г. в 21:31, Ilya Kamenshchikov <notifications@github.com>:

**Comment by reef425** [comment]
Забыл совcем, в разных системах unix*, windows*.  Потоки реализованы по разному, для гарантирования потокобезопасности и кроссплатформенности используем данный метод.

**Comment by reef425** [comment]
Вообще идеальный вариант для построения потока в Qt описан в [Правильное использование QThread](https://habr.com/post/150274/)

**Comment by ikamensh** [comment]
Вопрос 1. Наш GUI уже многопоточен или ты планируешь это на будущее?

Вопрос 2:
Если риск от многопоточности действительно есть для нашей графики, то наверняка существует пример ситуации в которой не используя сигналы и слоты мы сможем наблюдать ошибку. Ты не мог бы придумать / продемонстрировать это?
( например в отдельном бранче )
*** Возможно нам нужно понять рискованный сценарий на бумаге для начала. Обычно потокобезопасность сводится к Race Condition. Кто кого может обогнать в нашем приложении? ведь после того как сигнал прошел, графика отрисовывается обычным кодом python. (тем же самым который я бы использовал без slots & signals)

**Comment by reef425** [comment]
Закомментировал строку 12 в файле ui/triggers/animation_triggers.py
И добавил строку 13

Закомментировал строку 63 в файле GameLoopThread.py

После изменений, не корректно работает обновление экрана, где один раз юнит тобразился там картинка и остается. 
Вывод в лог
Demo Hero 5 with 1086 HP moves from (2,1) to (3,1)
Pirate 3 with 250 HP facing SOUTH turns counter-clockwise.
Mud Golem 4 with 425 HP moves from (2,2) to (2,1)
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
Pirate 3 with 250 HP facing EAST turns clockwise.
Pirate 3 with 250 HP facing SOUTH turns counter-clockwise.
Pirate 1 with 250 HP moves from (2,3) to (3,2)
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread
QObject::startTimer: Timers cannot be started from another thread

**Comment by reef425** [comment]
Использование потоков начинается с определения где возможно конкурирование потоков за общие данные.
Что бы правильно происходило обновление данных, добавляют глобальные блокировки.
Если поток простой можно обойтись блокировками, если нет необходимо учитывать возможные взаимные блокировки потоков. Добавляют использование паттернов семафоры.

Что бы не разбираться со всем этим можно просто использовать сигналы и слоты.

Поток в GUI, должен запускаться в основном потоке, если очень надо то правильно запускать GUI в отдельном процессе. Иначе отработка GUI будет происходить медленно и не корректно. (Обычно офисные юзеры говорят: я же быстро нажимаю, что он(компьютерная программа) медленно работает)

**Comment by ikamensh** [comment]
Хорошо, спасибо что показал пример проблемы. Я видел не доконца отрисованных юнитов. 
Я понял так > вызов на отрисовку юнита приходит как-бы асинхронно, в середине других графических процессов.
Думаю вопрос о том чтобы сейчас отказаться от слотов и сигналов снят.
По коду: давай писать комментом рядом с отправкой сигнала название слота куда он прийдет, так будет легче понять код.
