### ISSUE TITLE
Inheriting from object

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#4]
@reef425 

Я заметил патерн наследования от object и лишней линии в ините:

`class GameRootNode(object):

    def __init__(self):
        super(GameRootNode, self).__init__()
        self.scene = None`

Pydolons деляются только для python3, поэтому нам не нужно наследовать от обджекта.
Пожалуйста используй:

`class GameRootNode: 

    def __init__(self):
        self.scene = None`

Можешь почитать о рекомендациях сообщества тут:

https://stackoverflow.com/questions/4015417/python-class-inherits-object

> In Python 3: inherit from object if you are writing code that tries to be Python agnostic, that is, it needs to work both in Python 2 and in Python 3. Otherwise don't, it really makes no difference since Python inserts it for you behind the scenes. In

**Comment by reef425** [comment]
На самом деле классы у меня генерируются автоматом, пишу только название класса
Поправлю этот момент.

```
class FooClass(object):
    """docstring for FooClass."""
    def __init__(self, arg):
        super(FooClass, self).__init__()
        self.arg = arg```

Проверил действительно все так.

```class Foo:
...     def __init__(self):
...             self.arg = None
... 
 dir(Foo)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
 class Too(object):
...     def __init__(self):
...             self.arg = None
... 
 dir(Too)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']```

**Comment by ikamensh** [comment]
Спасибо!
