### ISSUE TITLE
Активки

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#5]
У нас есть deliverable:
1. Отображать поле боя 
  d. Есть возможность выбрать активки и выбрать для них цель, визуально видно находится ли игра в состоянии выбора цели или в обычном режиме движения по карте.

Относительно этого, код уже существует. 
Получить все активки можно так:
**_actives = unit.actives_**

Получить их возможные цели можно так
from mechanics.AI.SimGame import SimGame as DreamGame (уже используется в нашем launch.py)

**_game.get_possible_targets(active)_**

Тоесть нам нужно небольшое окошко где будут символы всех активок. 
active.owner_can_afford_activation()  - можно ли активировать в данный момент. Активки, для которых это False показываем серым цветом (они имеют иконку)

Серые активки при клике выводят сообщение о том что их нельзя активировать. я потом напишу логику чтобы жаловался на конкретную проблему - мана, стамина или хп

Нормальные активки либо активируются если active.targeting_cls == None
( active.activate(None) )
либо переводят игру в состояние выбора цели. Правый клик мышью это состояние прерывает. 
Если мы выбрали одну из предложеных целей (**_get_possible_targets(active)_**), то теперь мы активируем активку 
( active.activate(target) )

**Comment by reef425** [comment]
В данный момент реализовано:
> переводят игру в состояние выбора цели
- не верно работает целеукзатель

Вопрос по реализции, если происходит выбор цели,то игрок будет ограничен только выбором целивых клеток или нет?

**Comment by ikamensh** [comment]
Посмотрел на то как это выглядит у меня. Хочу уточнить:
Когда я говорил про скролл вниз, я имел ввиду просто небольшую кнопку типа тех что поднимают / скидывают характеристики в экране прокачки. По клику вниз тогда сменился бы весь ряд активок на один ряд ниже. Я не вижу преимуществ для пользователя от постепенного скролла - зачем ему видеть половину одного ряда и половину другого? 

Активки имеют иконку (пока что ресурсы не проставлены, все активки используют одну и ту же, но  твой элемент функционирует тем же образом) и по ним должен быть тултип.

**Comment by ikamensh** [comment]
По выбору цели: Если можно попробуй при выборе юнита привязать это к объекту юнита. Одна из запланированных фич это позволить до 3х юнитов на одной и той же клетке (они будут уменьшены и каскадно лежать друг под другом, но каждый частично выглядывает). 

Если игрок жмет не на валидную цель, то режим выбора цели отменяется. То же самое на правый клик мышью. Таким образом должно быть легко покинуть режим выбора цели.

**Comment by reef425** [comment]
Обновил и залил код. Настройка и добавление актиок вынесено в `addActiveButtons()`.
Добаление нового виджета через `addWidget(self, name)`
Ширина окна активок зависит от размера активки и количества колонок,

**Comment by ikamensh** [comment]
Хорошо, я смог нацелить атаку, все четко сработало.
Переодически бросается вот такая ошибка:

AttributeError: 'Actives' object has no attribute 'y'
Traceback (most recent call last):
  File "C:\Users\ikame\pydolons\ui\GameView.py", line 32, in mouseMoveEvent
    self.controller.mouseMoveEvent(e)
  File "C:\Users\ikame\pydolons\ui\GameController.py", line 42, in mouseMoveEvent
    self.gameRoot.gamePages.checkFocus(e.pos())
  File "C:\Users\ikame\pydolons\ui\GamePages\__init__.py", line 102, in checkFocus
    self.focus = self.gameMenu.checkFocus(pos)
  File "C:\Users\ikame\pydolons\ui\GamePages\GameMenuPage.py", line 93, in checkFocus
    if pos.y() > self.actives.y and pos.x() > self.actives.x and pos.x() < self.actives.x + self.actives.w:

AttributeError: 'Actives' object has no attribute 'y'

Может там называется width / height / w / h? getX? getY?

**Comment by reef425** [comment]
Обновил и залил код. фокус внутри активок работает нормально. Убрал прокрутку. Добавил кнопки пролистывания.

**Comment by ikamensh** [comment]
@reef425 
Активки работают. 
Нехватает:
1. По интерфейсу, я бы хотел чтобы выбор цели для активки происходил левым кликом. Правый клик во время выбора цели для активки должен прервать выбор цели и не иметь никаких других последствий.
2. Еще надо реализовать поддержку проверки на возможность активации. При клике надо проверить, что active.affordable(); если нет то надо вывести сообщение active.why_not_affordable().
3. Активка, которая вообще-то может быть активирована, может получить цель к которой она не применима. В таком случае active.affordable() == True, active.check_target(target) == False. Нужно вывести сообщение active.why_wrong_target( target )

сообщение я представляю себе примерно как сообщения VICTORY - пропадающий текст поверх остальных объектов. Потом можно будет добавить звук невозможной команды, как в винде.

**Comment by ikamensh** [comment]
устарело. При необходимости пересоздадим тред.
