### ISSUE TITLE
Запуск UI

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#8]
@reef425 
На данный момент скрипт запуска стал длинее и немного запутанее. Давай соберем запуск в один класс и предоставим понятный интерфейс. У нас будет некий объект контролирующий создание объектов DreamGame - одиночных подземелий и их отображение в UI.

1. фактически при запуске игры мы создаем UI, а потом соединяем объекты игры с UI. Тогда я бы мог контролировать lifecycle приложения и легче узнать результаты игры. 
нужен метод 
UI.connect_to_game( game : DreamGame ) 

было бы удобно если бы UI.connect_to_game можно было просто вызвать еще раз с новым объектом game, и тем самым загрузить след уровень.

Включение триггеров, обеспечивающие работу UI тоже можно поместить в UI.connect_to_game

**Comment by reef425** [comment]
Добавил  отметки времени, вывода в лог.
Как показывает вывод изображения загружаются синхронно и занимают в среднем 2 сек.
Звуки загружаются и декодируются асинхронно.

Как должен происходить запуск приложения.
* Основной поток
* Инит. UI
* Загрузка ресурсов(Можно сделать асинхронно).
* Инит. the_game

* UI вызывает у Engine загрузку уровня the_game.startLevel('level dungeon 1')
* После загрузки уровня в Engine, происходит загрузка интерфейса на основе данных об уровне.
* У  Engine запускается цикл игры с в отдельном потоке.(Запуск цикла игры не привязан к конкретно уровню)
* По завершению уровня или если пользователь решил завершить игру вызываем the_game.stopLevel(), the_game.pauseLevel(), game.resumeLevel(), game.restartLevel()

На игровую механику 2 потока, на работу с вводом выводом может быть больше потоков.

**Comment by ikamensh** [comment]
Какие именно 2 потока используются для игровой логики?

**Comment by ikamensh** [comment]
Скрипт запуска стал понятнее. Архитектуру стоит задокументировать, но это будет отдельной темой в будущем.
