### ISSUE TITLE
Basic Unit - Direction Pointer

### ISSUE THREAD

**Issue by ikamensh** [ikamensh/drim_gam#9]
@reef425 
Привет! 
Посмотрел как работает визуализация текущего угла поворота. Вижу там есть 4 элемента из которых только 1 видим. 

Хотелось бы при повороте постепенно поворачивать угол поворота, такая визуализация будет лучше. Сложно ли заменить 4 объекта на один, вращающийся вокруг центра юнита?

**Comment by reef425** [comment]
Не сложно, но еще проще было сделать именно так, потому что не совсем ясно
было какую стрелку и какого размера использовать. Займусь этим как только
доделаю меню прокачки персонажа.

сб, 6 окт. 2018 г. в 14:05, Ilya Kamenshchikov <notifications@github.com>:

**Comment by reef425** [comment]
Direction Pointer - стрелка сейчас одна, добавил анимацию, но анимация работает не так как надо

**Comment by reef425** [comment]
Предлагаю проверить и закрыть задачу, если все работает.
Добавил пакет GameAnimation, module Animations.py, animation object Direction.py.
Анимации стрелки работает корректно.

**Comment by ikamensh** [comment]
Посмотрел на то как оно работает, классный прогресс. Тем не менее я смог найти случай когда она не корректно отображается - если не дать текущей анимации завершиться.
Попробуй очень быстро поворачиваться по или против часовой стрелке дважды - двойной клик на q / e. Иногда поворачиваешься то по часовой стрелке, то против - даже если всегда использовать только действие в одном и том же направлении.

Это небольшая неточность которую хотелось бы исправить. предлагаю так: если текущая анимация не завершена, то следующая кладется в очередь, и скорость обеих анимаций удваивается.

Еще, в будущем планирую такую настройку в опциях как скорость анимации. Если не сложно заложи параметр который потом можно будет глобально менять.
Спасибо!

**Comment by reef425** [comment]
> Еще, в будущем планирую такую настройку в опциях как скорость анимации. Если не сложно заложи параметр который потом можно будет глобально менять.

Скорость зависит от времени воспроизведения, есть описание в Animations.
Animations -- построен по паттерну Factory Method.

**Comment by ikamensh** [comment]
Я имплементировал постепенный поворот.
